### ISSUE TITLE
Doesn't build with attoparsec 0.14.2

### ISSUE THREAD

**Issue by felixonmars** [blamario/input-parsers#4]
We probably need a more strict bound here?

```
[4 of 5] Compiling Text.Parser.Input ( src/Text/Parser/Input.hs, dist/build/Text/Parser/Input.dyn_o )

src/Text/Parser/Input.hs:400:10: error:
    • No instance for (LookAheadParsing Attoparsec.Char8.Parser)
        arising from the superclasses of an instance declaration
    • In the instance declaration for
        ‘InputParsing Attoparsec.Char8.Parser’
    |
400 | instance InputParsing Attoparsec.Parser where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Text/Parser/Input.hs:402:15: error:
                         (Data.Attoparsec.Internal.Types.Parser ByteString))
        arising from a use of ‘lookAhead’
    • In the expression: lookAhead Attoparsec.Char8.takeByteString
      In an equation for ‘getInput’:
          getInput = lookAhead Attoparsec.Char8.takeByteString
      In the instance declaration for
        ‘InputParsing Attoparsec.Char8.Parser’
    |
402 |    getInput = lookAhead Attoparsec.takeByteString
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Text/Parser/Input.hs:412:10: error:
    • No instance for (CharParsing Attoparsec.Char8.Parser)
        arising from the superclasses of an instance declaration
    • In the instance declaration for
        ‘InputCharParsing Attoparsec.Char8.Parser’
    |
412 | instance InputCharParsing Attoparsec.Parser where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

...
```

**Comment by blamario** [comment]
It builds for me, with `cabal build --constraint 'attoparsec == 0.14.2'`. What's your environment?

**Comment by felixonmars** [comment]
I'm on Arch Linux x86_64 with GHC 9.0.2. Probably some other dependencies are different then. I'll take a deeper look, sorry.

**Comment by blamario** [comment]
No problem.

**Comment by felixonmars** [comment]
It seems `cabal build --constraint 'attoparsec == 0.14.2'` disables the `attoparsec` flag automatically for some unknown reason. Force the flag and specify a suitable `attoparsec` would still reproduce this failure here:

```
$ cabal build --constraint 'attoparsec == 0.14.2'
Resolving dependencies...
Build profile: -w ghc-9.0.2 -O1
In order, the following will be built (use -v for more details):
 - input-parsers-0.2.3.1 (lib) (first run)
Configuring library for input-parsers-0.2.3.1..
Preprocessing library for input-parsers-0.2.3.1..
Building library for input-parsers-0.2.3.1..
[1 of 5] Compiling Text.Parser.Input.Position ( src/Text/Parser/Input/Position.hs, /home/felix/projects/input-parsers/dist-newstyle/build/x86_64-linux/ghc-9.0.2/input-parsers-0.2.3.1/build/Text/Parser/Input/Position.dyn_o )
[2 of 5] Compiling Text.Parser.Internal ( src/Text/Parser/Internal.hs, /home/felix/projects/input-parsers/dist-newstyle/build/x86_64-linux/ghc-9.0.2/input-parsers-0.2.3.1/build/Text/Parser/Internal.dyn_o )
[3 of 5] Compiling Text.Parser.Wrapper ( src/Text/Parser/Wrapper.hs, /home/felix/projects/input-parsers/dist-newstyle/build/x86_64-linux/ghc-9.0.2/input-parsers-0.2.3.1/build/Text/Parser/Wrapper.dyn_o )
[4 of 5] Compiling Text.Parser.Input ( src/Text/Parser/Input.hs, /home/felix/projects/input-parsers/dist-newstyle/build/x86_64-linux/ghc-9.0.2/input-parsers-0.2.3.1/build/Text/Parser/Input.dyn_o )
[5 of 5] Compiling Text.Parser.Deterministic ( src/Text/Parser/Deterministic.hs, /home/felix/projects/input-parsers/dist-newstyle/build/x86_64-linux/ghc-9.0.2/input-parsers-0.2.3.1/build/Text/Parser/Deterministic.dyn_o )
$ cabal build --constraint 'attoparsec == 0.14.2' -fattoparsec
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: input-parsers-0.2.3.1 (user goal)
[__1] trying: input-parsers:+attoparsec
[__2] next goal: attoparsec (dependency of input-parsers +attoparsec)
[__2] rejecting: attoparsec-0.14.4/installed-Fdv8BBOg37BEeo2D3tptKE,
attoparsec-0.13.2.4, attoparsec-0.13.2.3, attoparsec-0.13.2.2,
attoparsec-0.13.2.1, attoparsec-0.13.2.0, attoparsec-0.13.1.0,
attoparsec-0.13.0.2, attoparsec-0.13.0.1, attoparsec-0.13.0.0,
attoparsec-0.12.1.6, attoparsec-0.12.1.5, attoparsec-0.12.1.4,
attoparsec-0.12.1.3, attoparsec-0.12.1.2, attoparsec-0.12.1.1,
attoparsec-0.12.1.0, attoparsec-0.12.0.0, attoparsec-0.11.3.4,
attoparsec-0.11.3.3, attoparsec-0.11.3.2, attoparsec-0.11.3.1,
attoparsec-0.11.3.0, attoparsec-0.11.2.1, attoparsec-0.11.1.0,
attoparsec-0.10.4.0, attoparsec-0.10.3.0, attoparsec-0.10.2.0,
attoparsec-0.10.1.1, attoparsec-0.10.1.0, attoparsec-0.10.0.3,
attoparsec-0.10.0.2, attoparsec-0.10.0.1, attoparsec-0.10.0.0,
attoparsec-0.9.1.2, attoparsec-0.9.1.1, attoparsec-0.9.0.0,
attoparsec-0.8.6.1, attoparsec-0.8.6.0, attoparsec-0.8.5.3,
attoparsec-0.8.5.2, attoparsec-0.8.5.1, attoparsec-0.8.5.0,
attoparsec-0.8.4.0, attoparsec-0.8.3.0, attoparsec-0.8.2.0,
attoparsec-0.8.1.1, attoparsec-0.8.1.0, attoparsec-0.8.0.2,
attoparsec-0.8.0.1, attoparsec-0.8.0.0, attoparsec-0.7.2, attoparsec-0.7.1,
attoparsec-0.6, attoparsec-0.5.1, attoparsec-0.5, attoparsec-0.4 (constraint
from command line flag requires ==0.14.2)
[__2] fail (backjumping, conflict set: attoparsec, input-parsers,
input-parsers:attoparsec)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: attoparsec, input-parsers,
input-parsers:attoparsec
$ cabal build --constraint 'attoparsec == 0.14.4' -fattoparsec
Resolving dependencies...
Build profile: -w ghc-9.0.2 -O1
In order, the following will be built (use -v for more details):
 - input-parsers-0.2.3.1 (lib) (configuration changed)
Configuring library for input-parsers-0.2.3.1..
Preprocessing library for input-parsers-0.2.3.1..
Building library for input-parsers-0.2.3.1..
[4 of 5] Compiling Text.Parser.Input ( src/Text/Parser/Input.hs, /home/felix/projects/input-parsers/dist-newstyle/build/x86_64-linux/ghc-9.0.2/input-parsers-0.2.3.1/build/Text/Parser/Input.dyn_o ) [Data.Attoparsec.Text changed]

src/Text/Parser/Input.hs:400:10: error:
...(same as original report)
```

**Comment by felixonmars** [comment]
It seems `cabal build --constraint 'attoparsec == 0.14.2'` disables the `attoparsec` flag automatically for some unknown reason (for example, if your hackage index db isn't up-to-date so no 0.14.2 is present?). Force the flag or update the db would still reproduce this failure here.

With an out-of-date hackage index db:
```
$ cabal build --constraint 'attoparsec == 0.14.2'
Resolving dependencies...
Build profile: -w ghc-9.0.2 -O1
In order, the following will be built (use -v for more details):
 - input-parsers-0.2.3.1 (lib) (first run)
Configuring library for input-parsers-0.2.3.1..
Preprocessing library for input-parsers-0.2.3.1..
Building library for input-parsers-0.2.3.1..
[1 of 5] Compiling Text.Parser.Input.Position ( src/Text/Parser/Input/Position.hs, /home/felix/projects/input-parsers/dist-newstyle/build/x86_64-linux/ghc-9.0.2/input-parsers-0.2.3.1/build/Text/Parser/Input/Position.dyn_o )
[2 of 5] Compiling Text.Parser.Internal ( src/Text/Parser/Internal.hs, /home/felix/projects/input-parsers/dist-newstyle/build/x86_64-linux/ghc-9.0.2/input-parsers-0.2.3.1/build/Text/Parser/Internal.dyn_o )
[3 of 5] Compiling Text.Parser.Wrapper ( src/Text/Parser/Wrapper.hs, /home/felix/projects/input-parsers/dist-newstyle/build/x86_64-linux/ghc-9.0.2/input-parsers-0.2.3.1/build/Text/Parser/Wrapper.dyn_o )
[4 of 5] Compiling Text.Parser.Input ( src/Text/Parser/Input.hs, /home/felix/projects/input-parsers/dist-newstyle/build/x86_64-linux/ghc-9.0.2/input-parsers-0.2.3.1/build/Text/Parser/Input.dyn_o )
[5 of 5] Compiling Text.Parser.Deterministic ( src/Text/Parser/Deterministic.hs, /home/felix/projects/input-parsers/dist-newstyle/build/x86_64-linux/ghc-9.0.2/input-parsers-0.2.3.1/build/Text/Parser/Deterministic.dyn_o )
$ cabal build --constraint 'attoparsec == 0.14.2' -fattoparsec
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: input-parsers-0.2.3.1 (user goal)
[__1] trying: input-parsers:+attoparsec
[__2] next goal: attoparsec (dependency of input-parsers +attoparsec)
[__2] rejecting: attoparsec-0.14.4/installed-Fdv8BBOg37BEeo2D3tptKE,
attoparsec-0.13.2.4, attoparsec-0.13.2.3, attoparsec-0.13.2.2,
attoparsec-0.13.2.1, attoparsec-0.13.2.0, attoparsec-0.13.1.0,
attoparsec-0.13.0.2, attoparsec-0.13.0.1, attoparsec-0.13.0.0,
attoparsec-0.12.1.6, attoparsec-0.12.1.5, attoparsec-0.12.1.4,
attoparsec-0.12.1.3, attoparsec-0.12.1.2, attoparsec-0.12.1.1,
attoparsec-0.12.1.0, attoparsec-0.12.0.0, attoparsec-0.11.3.4,
attoparsec-0.11.3.3, attoparsec-0.11.3.2, attoparsec-0.11.3.1,
attoparsec-0.11.3.0, attoparsec-0.11.2.1, attoparsec-0.11.1.0,
attoparsec-0.10.4.0, attoparsec-0.10.3.0, attoparsec-0.10.2.0,
attoparsec-0.10.1.1, attoparsec-0.10.1.0, attoparsec-0.10.0.3,
attoparsec-0.10.0.2, attoparsec-0.10.0.1, attoparsec-0.10.0.0,
attoparsec-0.9.1.2, attoparsec-0.9.1.1, attoparsec-0.9.0.0,
attoparsec-0.8.6.1, attoparsec-0.8.6.0, attoparsec-0.8.5.3,
attoparsec-0.8.5.2, attoparsec-0.8.5.1, attoparsec-0.8.5.0,
attoparsec-0.8.4.0, attoparsec-0.8.3.0, attoparsec-0.8.2.0,
attoparsec-0.8.1.1, attoparsec-0.8.1.0, attoparsec-0.8.0.2,
attoparsec-0.8.0.1, attoparsec-0.8.0.0, attoparsec-0.7.2, attoparsec-0.7.1,
attoparsec-0.6, attoparsec-0.5.1, attoparsec-0.5, attoparsec-0.4 (constraint
from command line flag requires ==0.14.2)
[__2] fail (backjumping, conflict set: attoparsec, input-parsers,
input-parsers:attoparsec)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: attoparsec, input-parsers,
input-parsers:attoparsec
```

After running `cabal update`:
```
$ cabal build --constraint 'attoparsec == 0.14.2'
Resolving dependencies...
Build profile: -w ghc-9.0.2 -O1
In order, the following will be built (use -v for more details):
 - attoparsec-0.14.2 (lib) (requires download & build)
 - input-parsers-0.2.3.1 (lib) (configuration changed)
Downloading  attoparsec-0.14.2
Downloaded   attoparsec-0.14.2
Starting     attoparsec-0.14.2 (lib)
Building     attoparsec-0.14.2 (lib)
Installing   attoparsec-0.14.2 (lib)
Completed    attoparsec-0.14.2 (lib)
Configuring library for input-parsers-0.2.3.1..
Preprocessing library for input-parsers-0.2.3.1..
Building library for input-parsers-0.2.3.1..
[4 of 5] Compiling Text.Parser.Input ( src/Text/Parser/Input.hs, /home/felix/projects/input-parsers/dist-newstyle/build/x86_64-linux/ghc-9.0.2/input-parsers-0.2.3.1/build/Text/Parser/Input.dyn_o ) [Data.Attoparsec.Text changed]

src/Text/Parser/Input.hs:400:10: error:
...(same as original report)
```

**Comment by blamario** [comment]
Sorry, but I'm failing to reproduce the problem here.

**Comment by felixonmars** [comment]
I think I found the problem. My configuration of `parsers` lacks attoparsec support due to outdated bounds & auto flags. Sorry again!
